//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SklepMuzycznyMVC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class szkolaEntities : DbContext
    {
        public szkolaEntities()
            : base("name=szkolaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<gatunek> gatuneks { get; set; }
        public DbSet<klient> klients { get; set; }
        public DbSet<pracownicy> pracownicies { get; set; }
        public DbSet<towar> towars { get; set; }
        public DbSet<wykonawca> wykonawcas { get; set; }
        public DbSet<wytwornia> wytwornias { get; set; }
        public DbSet<zamowienia> zamowienias { get; set; }
        public DbSet<towar_zamowienie> towar_zamowienie { get; set; }
    }
}
