//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SklepMuzyczny
{
    using System;
    using System.Collections.Generic;
    
    public partial class klient
    {
        public klient()
        {
            this.koszyk = new HashSet<koszyk>();
            this.zamowienia = new HashSet<zamowienia>();
        }
    
        public int idKlienta { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public int Telefon { get; set; }
        public string Adres { get; set; }
        public int Nr_konta { get; set; }
    
        public virtual ICollection<koszyk> koszyk { get; set; }
        public virtual ICollection<zamowienia> zamowienia { get; set; }
    }
}
