//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SklepMuzyczny
{
    using System;
    using System.Collections.Generic;
    
    public partial class koszyk
    {
        public int idTowaru { get; set; }
        public int idKlienta { get; set; }
        public int Ilosc { get; set; }
    
        public virtual klient klient { get; set; }
        public virtual towar towar { get; set; }
    }
}
