//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SklepMuzyczny
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class szkolaEntities5 : DbContext
    {
        public szkolaEntities5()
            : base("name=szkolaEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<gatunek> gatunek { get; set; }
        public DbSet<klient> klient { get; set; }
        public DbSet<towar> towar { get; set; }
        public DbSet<user> user { get; set; }
        public DbSet<wykonawca> wykonawca { get; set; }
        public DbSet<wytwornia> wytwornia { get; set; }
        public DbSet<zamowienia> zamowienia { get; set; }
        public DbSet<koszyk> koszyk { get; set; }
        public DbSet<towar_zamowienie> towar_zamowienie { get; set; }
    }
}
