//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SklepMuzyczny
{
    using System;
    using System.Collections.Generic;
    
    public partial class towar
    {
        public towar()
        {
            this.koszyk = new HashSet<koszyk>();
            this.towar_zamowienie = new HashSet<towar_zamowienie>();
        }
    
        public int idTowaru { get; set; }
        public int idWykonawcy { get; set; }
        public int idGatunku { get; set; }
        public string Nazwa { get; set; }
        public int Cena { get; set; }
        public System.DateTime Rok_wyd { get; set; }
        public int Ilosc_cd { get; set; }
    
        public virtual gatunek gatunek { get; set; }
        public virtual ICollection<koszyk> koszyk { get; set; }
        public virtual ICollection<towar_zamowienie> towar_zamowienie { get; set; }
        public virtual wykonawca wykonawca { get; set; }
    }
}
