//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SklepMuzyczny
{
    using System;
    using System.Collections.Generic;
    
    public partial class wykonawca
    {
        public wykonawca()
        {
            this.towar = new HashSet<towar>();
        }
    
        public int idWykonawcy { get; set; }
        public int idWytwórni { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
    
        public virtual ICollection<towar> towar { get; set; }
        public virtual wytwornia wytwornia { get; set; }
    }
}
