//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SklepMuzyczny
{
    using System;
    using System.Collections.Generic;
    
    public partial class wytwornia
    {
        public wytwornia()
        {
            this.wykonawca = new HashSet<wykonawca>();
        }
    
        public int idWytworni { get; set; }
        public string Nazwa { get; set; }
    
        public virtual ICollection<wykonawca> wykonawca { get; set; }
    }
}
