//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SklepMuzyczny
{
    using System;
    using System.Collections.Generic;
    
    public partial class zamowienia
    {
        public zamowienia()
        {
            this.towar_zamowienie = new HashSet<towar_zamowienie>();
        }
    
        public int idZamowienia { get; set; }
        public int idKlienta { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual klient klient { get; set; }
        public virtual ICollection<towar_zamowienie> towar_zamowienie { get; set; }
    }
}
